title: sloanzhang Blog
email: sloanzhang2017@gmail.com
description: 另一种技术的生活方式


# Build settings
permalink: :title
paginate: 1
paginate_path: "page:num"
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
